### ISSUE TITLE
Constant reconnections

### ISSUE THREAD

**Issue by stevesims** [algonauti/ember-cable#11]
I'm seeing the `cable` websocket connection get dropped and re-established approximately once every 10s.

I had foolishly been languishing on my own branch until today thus I've only just updated my app to use the latest version.  I suspect this may be related to the refactor that moved `connection_monitor` into a separate package, and/or changes relating to `init`, but haven't had a chance to investigate any deeper.  As far as I can tell by looking at the diffs this is the only change that could be causing this problem - it feels like the connection monitor isn't properly detecting that the cable has been opened successfully.

**Comment by safeforge** [comment]
@stevesims please provide more informations. rails version? ember version? ember-cable version?

**Comment by stevesims** [comment]
Yeah - sorry - I was on ember 2.4.5, ember-cable 0.5.0 (latest master), and Rails we're running 5.0 beta 3

Have just updated to Rails 5.0.0 and I can see that the `ping` message format has changed, which would explain why things had been broken.  With the new format of messages it works fine.

(As an aside I had a feeling, looking at the code, that if the connection got busy the client could end up dropping the connection, based on the assumption that the server wouldn't need to send any `ping` messages.  On experimenting it seems that currently Rails will always sending `ping` messages down the cable, even when the cable it's otherwise been busy.)

Closing this issue, as upgrading my Rails was the solution.
