### ISSUE TITLE
Destroy consumers

### ISSUE THREAD

**Issue by KirillSuhodolov** [algonauti/ember-cable#12]
Hi, @algonauti
First of all thanks for this library, you safe my time.

I have the issue with destroy consumers or unsubscribe. I have many pages and component at the app, and when change url, I destroy components and do not need cable updates.

How can i do it with you library?

**Comment by safeforge** [comment]
Hi @KirillSuhodolov, thank you for using ember-cable, 

currently the consumer can't be destroyed by design, the best way to remove 
subscriptions is by own identifier. you can do it with some code like this:

```javascript
consumer.subscriptions.findAll(identifier).forEach( (subscription) => {
  consumer.subscriptions.remove(subscription);
});
```

**Comment by KirillSuhodolov** [comment]
@safeforge already found that i can save subscriber to variable and use it. Thanks.
