### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by ValentinTrinque** [algonauti/ember-cable#14]
Hi,

First of all thanks for your work, it's a nice package you made here :)

However, I am experiencing an issue regarding the `CONNECTING` state.

Everything works fine, I am actually recieving and sending messages from the server. However it seems the connecter try to send messages whereas the WebSocket isn't fully connected.

Maybe the `this.isOpen()` is not returning the right answer ?

# Info

- ember-cli: 2.8.0
- node: 7.4.0
- os: darwin x64
- ember-cable: 0.5.0

# Backtrace 

```
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Class.send (http://cad.dev/assets/vendor.js:94112:31)
    at Class.send (http://cad.dev/assets/vendor.js:94284:30)
    at Class.sendCommand (http://cad.dev/assets/vendor.js:94416:30)
    at http://cad.dev/assets/vendor.js:94360:15
    at Array.forEach (native)
    at Class.reload (http://cad.dev/assets/vendor.js:94359:33)
    at Class.open (http://cad.dev/assets/vendor.js:94176:44)
send @ connection.js:16
send @ consumer.js:14
sendCommand @ subscriptions.js:87
(anonymous) @ subscriptions.js:31
reload @ subscriptions.js:30
open @ connection.js:80
```

# Error location

```js
send: function send(data) {
  if (this.isOpen()) {
    this.get('webSocket').send(JSON.stringify(data));    # <=
  }
},
```

### Edit
1. Add ember environment information

**Comment by safeforge** [comment]
hey @ValentinTrinque thank you for using ember-cable. can you give me a rails version?

**Comment by ValentinTrinque** [comment]
Hi, I am using Rails 5.0.1

**Comment by carmelone** [comment]
This problem is very annoing, I have it randomly with or without SSL connection.

**Comment by safeforge** [comment]
@carmelone can you report your stack? I'm trying to reproduce this issue with dummy application without success.

**Comment by ValentinTrinque** [comment]
This can be relating to a Rails bug. 

Here is an quote from the [Rails 5.1 beta changelog](https://github.com/rails/rails/blob/v5.1.0.beta1/actioncable/CHANGELOG.md) : 
> Prevent race where the client could receive and act upon a subscription confirmation before the channel's subscribed method completed.
> Fixes #25381.
> Vladimir Dementyev

**Comment by safeforge** [comment]
@ValentinTrinque thank you

**Comment by johnunclesam** [comment]
I'm sorry. This problem has come back even now, after upgrading to version 5.1.0.beta1.
I start to think that it is wrong the way we use something.
