### ISSUE TITLE
Pass the main container to the ember-cable objects

### ISSUE THREAD

**Issue by ValentinTrinque** [algonauti/ember-cable#15]
I have trouble using your package when trying to access application services from my subscription object. I can't call `service.inject()` from my subscription objects.

In your README examples, you creates your channel subscriptions directly into the ember component / controller / service. The javascript object you are passing is able to call the application services because the object capture the context around him. So you are able to access `this` variable etc...

I have a slightly different approach, I have a Mixin :

```js
import Ember from "ember";

const { debug, Mixin } = Ember;

export default Mixin.create({
  store: inject.service(),

  isConnected: false,

  connected() {
    this.set("isConnected", true);
  },

  disconnected() {
    this.set("isConnected", false);
  },

  received(data) {
    this.get("store").pushPayload(data);
  },
});
```

I pass it to your cable service t:

```js
// My channel builder service
channelInfo = "MyRailsChannel";
channelMixin = MyRailsSubscription;
return this.get("consumer").subscriptions.create(channelInfo, channelMixin);
```

This could work but I experience an issue telling me :
```
Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.
```

I appears that your objects (`Comsumer`, `Subscriptions`, `Subscription`) aren't linked to the main container of the application, the App container, which prevent me from calling services inside my subscription objet.

The solution is to pass `Ember.getOwner(this).ownerInjection()` everywhere you create your objects.

Example, in your `createConsumer` function :

```js
createConsumer(url) {
  return Consumer.create(Ember.getOwner(this).ownerInjection(), { url: url });
}
```

What do you think ?

**Comment by safeforge** [comment]
@ValentinTrinque this is a great feature, can you test master branch before to release a new version? 

thank you for your effort

**Comment by ValentinTrinque** [comment]
@safeforge Wow ! Fast ! That's highly appreciable !

I will test it for tomorrow morning since our company is using your package ;)

**Comment by johnunclesam** [comment]
Don't forget to update the Readme tutorial, please, for newbies like me.

**Comment by ValentinTrinque** [comment]
Good news, I have tested it against the master branch and all seems to work as expected !

I guess it's ready to be merge.

Note: Maybe we could add some doc to show that's possible :)

**Comment by safeforge** [comment]
I've added a small example in README

```javascript
   // Using mixin and inject your services
    var channelMixin = Ember.Mixin.create({
      store: Ember.inject.service(),

      received(data) {
        this.get("store").pushPayload(data);
      }
    });

    consumer.subscriptions.create({ channel: 'NotificationChannel' }, channelMixin);
```

**Comment by ValentinTrinque** [comment]
That's nice ! Thank you for your reactivity.

Are you planing to release a new version of your package ? I would rather specify a package version inside my `package.json` instead of the git url ;)
