### ISSUE TITLE
Ability to completely disconnect from websockets

### ISSUE THREAD

**Issue by carsol** [algonauti/ember-cable#16]
Hey there,
Is there a way to have the cable connection not attempt to reconnect after a set number of retries after getting disconnected? I see in the `ConnectionMonitor` you continuously `poll()` but there is no way to stop it.

Cheers,
Carlos

**Comment by safeforge** [comment]
hi @carsol at the moment is not possible to disconnect after a set number of retries, I'm little bit busy in the next weeks - feel free to open a PR I'll be happy to integrate it in the next release.

**Comment by carsol** [comment]
Thank you @safeforge ! I ended up needing this to meet a requirement but it looks like I don't need it anymore. If that changes I will definitely create a PR :)
