### ISSUE TITLE
Endless `poll` loop doesn't play well with tests

### ISSUE THREAD

**Issue by YoranBrondsema** [algonauti/ember-cable#19]
The endless `poll` makes it that tests never end. It would be good to find a way to only perform one poll for instance when in the testing environment. This I think will enable true component integration tests with something like `mock-socket`.

I can come up with a PR if you think this is a good idea.

**Comment by jakeonfire** [comment]
@YoranBrondsema I also ran into this issue and ended up stubbing out the cable service in tests - is there any work-around in the short term? i tried disconnecting the WebSocket via mock-socket but couldn't figure it out...
