### ISSUE TITLE
ember-cable seems to be disconnecting and connecting

### ISSUE THREAD

**Issue by sunapi386** [algonauti/ember-cable#4]
WebSocket implementation from ember-cable seems to be disconnecting and connecting. 

It should only automatically reconnect if the connection is dropped. Currently it seems every 5 seconds, ember-cable is making a new websocket connection and then after 1 second it disconnecting the existing connection to use the new connection.

I made a repo describing this problem. It includes rails api and ember.

https://github.com/sunapi386/chatroom

**Comment by safeforge** [comment]
@sunapi386 can you update to version `0.4.0` and leave a feedback?

**Comment by sunapi386** [comment]
@safeforge looks good! Ember-cable no longer continues connect/disconnect. Functionality still good.

**Comment by safeforge** [comment]
thanks @sunapi386

**Comment by GarPit** [comment]
@safeforge Awesome, for me works too, thanks!
