### ISSUE TITLE
Closing connection

### ISSUE THREAD

**Issue by l33z3r** [algonauti/ember-cable#40]
Hi guys, I am struggling to find a way to disconnect the web socket when I no longer need it. 
Do I simply call destroy on the consumer which in turn will call willDestroy ?

**Comment by newyork-anthonyng** [comment]
Late response, but see here: https://github.com/algonauti/ember-cable/issues/12#issuecomment-259920062

For myself, `service.destroy` seemed to work.
```js
this.get('cableService').destroy();
```

**Comment by l33z3r** [comment]
Great thanks!
