### ISSUE TITLE
Problem with cookies.signed

### ISSUE THREAD

**Issue by GarPit** [algonauti/ember-cable#5]
Is this working the same way as action_cable.js? I mean I can't setup current user on Rails side via cookies.signed

**Comment by algodave** [comment]
Could you provide some more detail about the issue you're having, and why you *can't* use Rails' `cookie.signed`? Thanks!

**Comment by GarPit** [comment]
Because I send JSON from server (backend app (Rails, ActionCable) and frontend app(Ember)). So my question is how to make connection authentication?

**Comment by joostverdoorn** [comment]
@GarPit I think the only way to handle authentication, besides using a cookie, is passing some query parameters in the url:

```javascript
let consumer = this.get('cable').createConsumer(`ws://localhost:28080?access_token=${accessToken}`);
```

**Comment by safeforge** [comment]
@GarPit any progress?

**Comment by GarPit** [comment]
@safeforge actually no, but @joostverdoorn pointer to the most simple way to do this. I have problem with this because I receive authentication info in HTTP header via https://github.com/lynndylanhurley/devise_token_auth

**Comment by safeforge** [comment]
yeah probably the best way is to use `token` param
