### ISSUE TITLE
Is there the way we can put the token in the headers?

### ISSUE THREAD

**Issue by Uysim** [algonauti/ember-cable#50]
I would be better for security if we can put token in the header via connection

**Comment by Pro777** [comment]
I agree. I am trying to standardize my jwt implementation on my app, so I am trying to pass the jwt in the 'Authorization' header.

**Comment by safeforge** [comment]
Sorry folks this really went out of my radar, unluckily seems to be not possible to use custom headers in the JavaScript WebSockets API and I agree with you which is not safe to use token in the url.

An alternative approach could be to use a `signed` cookie provided by rails. If your backend is `--api` only and the middleware `ActionDispatch::Cookies` is not available, then the signed message
 could be generated using `Rails.application.message_verifier` 

Here an example of the potential implementation


```ruby
# config/initializers/action_cable.rb
module ActionCable
  TOKEN_KEY = "your.token.key"

  def self.generate_ticket(id, expires_at: 1.days.from_now)
    message_verifier.generate([id, expires_at])
  end

  def self.verify_ticket(ticket)
    message_verifier.verify(ticket)
  rescue ActiveSupport::MessageVerifier::InvalidSignature
  end

  def self.message_verifier
    Rails.application.message_verifier(ActionCable::TOKEN_KEY)
  end
end
```

you can send the valid token in the user's object 

```ruby
  def actioncable_ticket
    ActionCable.generate_ticket(current_user.id)
  end
```

and set the right cookie in the webapp before to create a consumer. [ember-cookies](https://github.com/simplabs/ember-cookies) seems to be a good choice to work with cookie in the ember application.

```javascript
  // app/services/your_service.js

  // Services

  cable: service(),
  cookies: service(),
  session: service(),

  async start() {
    await this._refreshCookies();
    await this._createConsumer();
    await this._createSubscription();
  },

  async _refreshCookies() {
    this.get('cookies').write('your.token.key', get(this, 'session.currentUser.actioncableTicket'));
  },

  async _createConsumer() {
    set(this, 'consumer', this.cable.createConsumer(this.get('actionCableUrl')));
  },

  async _createSubscription() {
    let subscription = this.consumer.createSubscription('YourAwesomeChannel', {
      received: (message) => {
        // process message
      }
    });
    set(this, 'subscription', subscription);
  },

```
and then you can verify the credentials before to procede with authentication.

```ruby
# app/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    protected

    def find_verified_user
      user_id, expires_at = ActionCable.verify_ticket(actioncable_token)

      if user_id
        verified_user = User.find_by(id: user_id)
        if verified_user && expires_at > Time.now
          verified_user
        else
          reject_unauthorized_connection
        end
      else
        reject_unauthorized_connection
      end
    end

    def actioncable_token
      cookies.fetch(ActionCable::TOKEN_KEY) { nil }
    end
  end
end

```

I hope the current snippet of code can help to avoid to use the access token in the url, remember to use a secure websocket and in general make sure SSL is installed for the entire site.
