### ISSUE TITLE
Publish v1.1.0 to NPM

### ISSUE THREAD

**Issue by richard-viney** [algonauti/ember-cable#67]
Hi,

Is it possible to publish the latest version of this package to NPM? The latest on NPM is a few years old. Currently I'm putting this into my `package.json`:

```
"ember-cable": "github:algonauti/ember-cable#v1.1.0",
```

Thanks!

**Comment by safeforge** [comment]
@richard-viney the last version of ember-cable was deployed 11 days ago and it is available at https://www.npmjs.com/package/@algonauti/ember-cable
