### ISSUE TITLE
Ability to access active subscriptions

### ISSUE THREAD

**Issue by igorrKurr** [algonauti/ember-cable#7]
Currently, there is no way to access subscriptions that was created.
For instance, I've created a new `Notifications` subscription in `application` controller. There I can handle only `received` data. But what if I want to to send data to same subscription channel, but form another entity, like form `my-notification` component for example. Of course, we can create action in application controller and pass it to component, but there could lot of nested controllers/components, that could make code not very tidy.
And since we have cable in form of `Service`, that would be good to have sort of active subscriptions in it, to be able easily access any subscription application wide.
Hope that would be useful 😄

**Comment by algodave** [comment]
It seems like what you ask for can be achieved by invoking `notify()` or `notifyAll()` methods on `this.get('consumerService.consumer').subscriptions` - unless I am missing something?

**Comment by safeforge** [comment]
`findAll(identifier)` can be used to retrive all notifications
